name: Generate Sitemap

on:
  schedule:
    - cron: '0 3 * * *'  # 매일 오전 12시 KST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate sitemap.xml
        run: python generate.py

      - name: Commit sitemap.xml
        run: |
          git config user.name "sitemap-bot"
          git config user.email "sitemap-bot@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "update sitemap" || echo "No changes"
          git push
